name: Presubmits

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@dd2c410b088af7c0dc8046f3ac9a8f4148492a95 # v1
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v2

    - name: Set up Go
      uses: actions/setup-go@268d8c0ca0432bb2cf416faae41297df9d262d7f # v3.0.0
      with:
        go-version: 1.18
        check-latest: true

    - name: Build
      run: go build -v ./...

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@dd2c410b088af7c0dc8046f3ac9a8f4148492a95 # v1
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v2

    - name: Set up Go
      uses: actions/setup-go@268d8c0ca0432bb2cf416faae41297df9d262d7f # v3.0.0
      with:
        go-version: 1.18
        check-latest: true

    - name: Test
      run: go test -v -race -covermode=atomic -coverprofile=coverage.out ./...
    - name: Upload codecoverage
      uses: codecov/codecov-action@81cd2dc8148241f03f5839d295e000b8f761e378 # v3.0.0
      with:
        files: ./coverage.out
        verbose: true

  build-image:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@dd2c410b088af7c0dc8046f3ac9a8f4148492a95 # v1
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v2

    - name: Set up Go
      uses: actions/setup-go@268d8c0ca0432bb2cf416faae41297df9d262d7f # v3.0.0
      with:
        go-version: 1.18
        check-latest: true

    - name: Install ko
      uses: imjasonh/setup-ko@78eea08f10db87a7a23a666a4a6fe2734f2eeb8d # v0.5

    - name: Local Image
      run: make ko-local
