name: Release

on:
  push:
    branches:
      - main
    tags:
      - v*

env:
  COSIGN_EXPERIMENTAL: true

jobs:
  build-image:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      packages: write
      contents: read

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@34cbc43f0b10c9dda284e663cf43c2ebaf83e956 # v1
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v3.0.0

    - name: Set up Go
      uses: actions/setup-go@f6164bd8c8acb4a71fb2791a8b6c4024ff038dab # v3.0.0
      with:
        go-version: 1.17.x

    - name: Install ko
      uses: imjasonh/setup-ko@2c3450ca27f6e6f2b02e72a40f2163c281a1f675 # v0.4

    - name: Install cosign
      uses: sigstore/cosign-installer@536b37ec5d5b543420bdfd9b744c5965bd4d8730 # v2.2.0

    - name: Log into ghcr.io
      uses: docker/login-action@dd4fa0671be5250ee6f50aedf4cb05514abda2c7 # v1.14.1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - run: |
        make ko-build
        make sign-images
