name: Release

on:
  push:
    branches:
      - main
    tags:
      - v*

env:
  COSIGN_EXPERIMENTAL: true

jobs:
  build-image:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      packages: write
      contents: read

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@dd2c410b088af7c0dc8046f3ac9a8f4148492a95 # v1
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.0

    - name: Set up Go
      uses: actions/setup-go@268d8c0ca0432bb2cf416faae41297df9d262d7f # v3.0.0
      with:
        go-version: 1.18
        check-latest: true

    - name: Install ko
      uses: imjasonh/setup-ko@ace48d793556083a76f1e3e6068850c1f4a369aa # v0.5

    - name: Install cosign
      uses: sigstore/cosign-installer@b3413d484cc23cf8778c3d2aa361568d4eb54679 # v2.2.0

    - name: Log into ghcr.io
      uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b # v1.14.1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - run: |
        make build-sign-images
